Dari-master4/Dari.Web/Controllers/MeubleController.cs
using Dari.Data.Infrastructure;
using Dari.Domain.Entities;
using Dari.service;
using Dari.Service;
using DariTn.web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dari.Web.Controllers
{
    public class MeubleController : Controller
    {

        IDataBaseFactory dbf;
        IUnitOfWork uow;
        IService<Annonce> ServiceAnnonce;
        IService<Rate> ServiceRate;
        IService<Client> ServiceClient;
        IService<CategorieMeub> CategorieService;
        IService<Meuble> MeubleService;
        public MeubleController()
        {
            dbf = new DataBaseFactory();
            uow = new UnitOfWork(dbf);
            ServiceAnnonce = new Service<Annonce>(uow);
            ServiceClient = new Service<Client>(uow);
            ServiceRate = new Service<Rate>(uow);
            CategorieService = new Service<CategorieMeub>(uow);
            MeubleService = new Service<Meuble>(uow);
        }
        // GET: Meuble
        public ActionResult Index()
        {
            return View(MeubleService.GetAll());
        }

        // GET: Meuble/Details/5
        public ActionResult Details(int id)
        {
            return View(MeubleService.GetById(id));
        }

        // GET: Meuble/Create
        public ActionResult Create()
        {
            ViewBag.CategoryMeubId = new SelectList(MeubleService.GetAll(), "CategoryMeubId", "Name");
            return View();

        }

        // POST: Meuble/Create
        [HttpPost]
        public ActionResult Create(Meuble MVM, HttpPostedFileBase file)
        {
            try
            {

                MVM.Image = file.FileName;
                if (file.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Content/"), file.FileName);
                    file.SaveAs(path);
                }
                MeubleService.Add(MVM);
                MeubleService.Commit();

                return RedirectToAction("Index");


            }
            catch (Exception e)
            {
                return Json(e.Message);
            }

        }

        // GET: Meuble/Edit/5
        public ActionResult Edit(int id)
        {



            return View(MeubleService.GetById(id));
        }

        // POST: Meuble/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Meuble MVM) // FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                MeubleService.Update(MVM);
                MeubleService.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        // GET: Meuble/Delete/5
        public ActionResult Delete(int id)
        {
            return View(MeubleService.GetById(id));
        }

        // POST: Meuble/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                MeubleService.Delete(MeubleService.GetById(id));
                MeubleService.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult statistique()
        {




            int A = 0;
            int B = 0;
            int C = 0;

            var MyCategory = CategorieService.GetAll();
            List<CategorieMeub> cc = new List<CategorieMeub>();
            foreach (var item in MyCategory)
            {
                cc.Add(item);
            }
            List<Meuble> p1 = new List<Meuble>();
            List<Meuble> p2 = new List<Meuble>();
            List<Meuble> p3 = new List<Meuble>();
            List<Meuble> p4 = new List<Meuble>();
            foreach (var itemm in MeubleService.GetAll().Where(e => e.CategoryMeubId == cc[0].CategoryMeubId))
            {
                p1.Add(itemm);
            }
            foreach (var itemm in MeubleService.GetAll().Where(e => e.CategoryMeubId == cc[1].CategoryMeubId))
            {
                p2.Add(itemm);
            }
            foreach (var itemm in MeubleService.GetAll().Where(e => e.CategoryMeubId == cc[2].CategoryMeubId))
            {
                p3.Add(itemm);
            }
            foreach (var itemm in MeubleService.GetAll().Where(e => e.CategoryMeubId == cc[3].CategoryMeubId))
            {
                p4.Add(itemm);
            }



            ViewData["countA"] = p1.Count;
            ViewData["countB"] = p2.Count;
            ViewData["countC"] = p3.Count;
            ViewData["countD"] = p4.Count;





            return View();
        }


        [HttpPost]
        public ActionResult Index(string rech)
        {

            var list = MeubleService.GetAll();

            if (!String.IsNullOrEmpty(rech))
            {
                list = list.Where(m => m.Titre.Contains(rech)).ToList();

            }

            return View(list);

        }
    }


}

Dari-master4/Dari.Web/Controllers/RDVsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
using Dari.Data;
using Dari.Domain.Entities;
using Dari.Service;
using Dari.Data.Infrastructure;

namespace Dari.Web.Controllers
{
    public enum FlashMessageType
    {
        Success, Warning, Error
    }


    public class RDVsController : Controller
    {


        public void SetFlash(FlashMessageType type, string text)
        {
            TempData["FlashMessage.Type"] = type;
            TempData["FlashMessage.Text"] = text;
        }

        IDataBaseFactory dbf;
        IUnitOfWork uow;
        private Context db = new Context();
        IServiceRDV rs = new ServiceRDV();
        IServiceAnnonce sa;

        public RDVsController()
        {
            dbf = new DataBaseFactory();
            uow = new UnitOfWork(dbf);
            sa = new ServiceAnnonce(uow);
        }

        // GET: RDVs
        public ActionResult Index()
        {
            var rDV = db.RDV.Include(r => r.annonce).Include(r => r.visiteur);
            return View(rDV.ToList());
        }

        // GET: RDVs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RDV rDV = rs.GetById((int)id);
            if (rDV == null)
            {
                return HttpNotFound();
            }
            return View(rDV);
        }

        // GET: RDVs/Create
        public ActionResult Create(int Id)
        {
            ViewBag.annonceID = Id;
            //  ViewBag.visiteurID = new SelectList(db.Clients, "Id", "Nom");
            return View();
        }


        public ActionResult Accept(int rdvID)
        {
            RDV rdv = rs.GetById(rdvID);
            if (rdv.state.Equals(stateRDV.demand))
            {
                rdv.state = stateRDV.accepted;
                rs.Update(rdv);
                rs.Commit();
                SetFlash(FlashMessageType.Success, "RDV Accepted");
            }
            else
            {
                SetFlash(FlashMessageType.Warning, "Can't Accept RDV");
            }
            return RedirectToAction("Index");
        }





        public ActionResult Calender()
        {
            TempData["idUser"] = User.Identity.GetUserId();
            return View();
        }

        public JsonResult GetRDVs()
        {

            int userconnect = Int32.Parse(User.Identity.GetUserId());
            var events = rs.GetAll().Where(t => t.visiteurID == userconnect);

            return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        public JsonResult GetRDVse(int id)
        {


            var events = rs.GetAll().Where(t => t.visiteurID == id);

            return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
































        public ActionResult Cancel(int rdvID)
        {
            RDV rdv = rs.GetById(rdvID);
            if (rdv.state.Equals(stateRDV.accepted))
            {
                DateTime d1 = DateTime.Now;
                DateTime d2 = d1.AddDays(1);
                int res = DateTime.Compare(d2, rdv.date);
                if (res < 0)
                {
                    rdv.state = stateRDV.canceled;
                    rs.Update(rdv);
                    rs.Commit();
                    SetFlash(FlashMessageType.Success, "RDV canceled");
                }
                else
                {
                    SetFlash(FlashMessageType.Error, "Too Late to cancel RDV");
                }

            }

            else
            {
                SetFlash(FlashMessageType.Warning, "Can't cancele RDV");
            }
            return RedirectToAction("Index");
        }


        public ActionResult Refus(int rdvID)
        {
            RDV rdv = rs.GetById(rdvID);
            if (rdv.state.Equals(stateRDV.demand))
            {
                rdv.state = stateRDV.refused;
                rs.Update(rdv);
                rs.Commit();
                SetFlash(FlashMessageType.Success, "RDV refused");
            }
            else
            {
                SetFlash(FlashMessageType.Warning, "Can't refused RDV");
            }
            return RedirectToAction("Index");
        }

        // POST: RDVs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int annonceId, [Bind(Include = "date")] RDV rDV)
        {
            if (ModelState.IsValid)
            {
                int connectedUserID = User.Identity.GetUserId<int>();
                rDV.annonceID = annonceId;
                rDV.state = stateRDV.demand;
                rDV.visiteurID = connectedUserID;
                rs.Add(rDV);
                rs.Commit();
                return RedirectToAction("Index", "Annoce");
            }

            ViewBag.annonceID = new SelectList(db.Annonces, "AnnonceId", "Description", rDV.annonceID);
            //ViewBag.visiteurID = new SelectList(db.Clients, "Id", "Nom", rDV.visiteurID);
            return View(rDV);
        }

        // GET: RDVs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RDV rDV = db.RDV.Find(id);
            if (rDV == null)
            {
                return HttpNotFound();
            }
            ViewBag.annonceID = new SelectList(db.Annonces, "AnnonceId", "Description", rDV.annonceID);
            // ViewBag.visiteurID = new SelectList(db.Clients, "Id", "Nom", rDV.visiteurID);
            return View(rDV);
        }

        // POST: RDVs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,date,visiteurID,annonceID,state")] RDV rDV)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rDV).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.annonceID = new SelectList(db.Annonces, "AnnonceId", "Description", rDV.annonceID);
            //   ViewBag.visiteurID = new SelectList(db.Clients, "Id", "Nom", rDV.visiteurID);
            return View(rDV);
        }

        // GET: RDVs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RDV rDV = db.RDV.Find(id);
            if (rDV == null)
            {
                return HttpNotFound();
            }
            return View(rDV);
        }

        // POST: RDVs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RDV rDV = db.RDV.Find(id);
            db.RDV.Remove(rDV);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Dari-master4/Dari.Web/Views/Shared/FlashMessage.cshtml
@using Dari.Web.Controllers
@{
    string text = (string)TempData["FlashMessage.Text"];
    string cssClass = null;
    if (!string.IsNullOrWhiteSpace(text))
    {
        FlashMessageType type = (FlashMessageType)TempData["FlashMessage.Type"];
        cssClass = type.ToString().ToLower();
    }
}
@if (!string.IsNullOrWhiteSpace(text))
{

    <div class="alert alert-@cssClass">
        <center>
            @text
        </center>
    </div>

}

Dari-master4/Dari.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Dari-master4/Dari.Web/Views/Shared/_LayoutFront.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Azenta Template">
    <meta name="keywords" content="Azenta, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Azenta | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/Content/Front/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/Front/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/Front/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/Content/Front/css/themify-icons.css" type="text/css">
    <link rel="stylesheet" href="~/Content/Front/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/Content/Front/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/Front/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/Front/css/magnific-popup.css" type="text/css">
    <link rel="stylesheet" href="~/Content/Front/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/Front/css/style.css" type="text/css">
    @RenderSection("stylesheets", required: false)
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Section Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="canvas-open">
        <i class="icon_menu"></i>
    </div>
    <div class="offcanvas-menu-wrapper">
        <div class="canvas-close">
            <i class="icon_close"></i>
        </div>
        <nav class="main-menu">
            <ul>
                <li><a href="@Url.Action("Index", "Annoce")">Annonce</a></li>
                <li><a href="@Url.Action("Index", "Meuble")">Meuble</a></li>
                <li><a href=@Url.Action("Index", "RDVs")>Mes Rendez Vous</a></li>
                <li><a href=@Url.Action("Calender", "RDVs")>Calendrier</a></li>
                <li><a href="./contact.html">Contact</a></li>
            </ul>
        </nav>
        <div class="nav-logo-right">
            <ul>
                <li>
                    <i class="icon_phone"></i>
                    <div class="info-text">
                        <span>Phone:</span>
                        <p>(+12) 345 6789</p>
                    </div>
                </li>
                <li>
                    <i class="icon_map"></i>
                    <div class="info-text">
                        <span>Address:</span>
                        <p>16 Creek Ave, <span>NY</span></p>
                    </div>
                </li>
                <li>
                    <i class="icon_mail"></i>
                    <div class="info-text">
                        <span>Email:</span>
                        <p>Info.cololib@gmail.com</p>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <!-- Offcanvas Menu Section End -->
    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="top-nav">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7">
                        <nav class="main-menu">
                            <ul>
                                <li><a href=@Url.Action("Index","Home")>Home</a></li>
                                <li><a href="@Url.Action("Index", "Annoce")">Annonce</a></li>
                                <li><a href="./about-us.html">Mes annonces</a></li>
                                <li><a href="@Url.Action("Index", "Meuble")">Meuble</a></li>
                                <li><a href=@Url.Action("Index", "RDVs")>Mes Rendez Vous</a></li>
                                <li><a href=@Url.Action("Calender", "RDVs")>Calendrier</a></li>
                                <li><a href="./property-details.html">Pages</a></li>
                                <li><a href="./contact.html">Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                    <div class="col-lg-5">
                        <div class="top-right">
                            <a href="@Url.Action("Create", "Annoce")" class="property-sub">Creer une Annonce</a>
                            <a href="@Url.Action("Indexx", "Annoce")" class="property-sub">Mes annonces</a>
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <div class="language-option">
                                    <span>User</span>
                                    <i class="fa fa-angle-down"></i>
                                    <div class="flag-dropdown">
                                        <ul>
                                            <li class="dropdown">
                                                <a href=@Url.Action("Login", "Account") class="property-sub">Login</a>

                                            </li>

                                            <li>
                                                <a href=@Url.Action("Register","Account") class="property-sub"> Register</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="language-option">
                                    <span>English</span>
                                    <i class="fa fa-angle-down"></i>
                                    <div class="flag-dropdown">
                                        <ul>
                                            <li class="dropdown">
                                                @User.Identity.Name

                                            </li>

                                            <li>
                                                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                                {   @Html.AntiForgeryToken()
                                                    //Logout
                                                    <input type="submit" value="Log out" />
                                                }
                                            </li>
                                        </ul>
                                    </div>
                                </div>

                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="nav-logo">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="logo">
                            <a href="./index.html"><img src="Content/img/logo.png" alt=""></a>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="nav-logo-right">
                            <ul>
                                <li>
                                    <i class="icon_phone"></i>
                                    <div class="info-text">
                                        <span>Phone:</span>
                                        <p>(+12) 345 6789</p>
                                    </div>
                                </li>
                                <li>
                                    <i class="icon_map"></i>
                                    <div class="info-text">
                                        <span>Address:</span>
                                        <p>16 Creek Ave, <span>NY</span></p>
                                    </div>
                                </li>
                                <li>
                                    <i class="icon_mail"></i>
                                    <div class="info-text">
                                        <span>Email:</span>
                                        <p>Info.cololib@gmail.com</p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header End -->
    @Html.Partial("FlashMessage")
    @RenderBody()
    <!-- Footer Section Begin -->
    <footer class="footer-section set-bg" data-setbg="~/Content/Front/img/footer-bg.jpg">
        <div class="container">
            <div class="footer-text">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="footer-logo">
                            <div class="logo">
                                <a href="#"><img src="~/Content/Front/img/footer-logo.png" alt=""></a>
                            </div>
                            <p>Subscribe our newsletter gor get notification about new updates.</p>
                            <form action="#" class="newslatter-form">
                                <input type="text" placeholder="Enter your email...">
                                <button type="submit"><i class="fa fa-location-arrow"></i></button>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-3 offset-lg-1">
                        <div class="footer-widget">
                            <h4>Property City</h4>
                            <ul>
                                <li><i class="fa fa-caret-right"></i> <a href="#">Florida</a></li>
                                <li><i class="fa fa-caret-right"></i> <a href="#">New York</a></li>
                                <li><i class="fa fa-caret-right"></i> <a href="#">Washington</a></li>
                                <li><i class="fa fa-caret-right"></i> <a href="#">Los Angeles</a></li>
                            </ul>
                            <ul>
                                <li><i class="fa fa-caret-right"></i> <a href="#">St Louis</a></li>
                                <li><i class="fa fa-caret-right"></i> <a href="#">Jacksonville</a></li>
                                <li><i class="fa fa-caret-right"></i> <a href="#">San Jose</a></li>
                                <li><i class="fa fa-caret-right"></i> <a href="#">San Diego</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="footer-widget">
                            <h4>Social</h4>
                            <ul class="social">
                                <li><i class="ti-facebook"></i> <a href="#">Facebook</a></li>
                                <li><i class="ti-instagram"></i> <a href="#">Instagram</a></li>
                                <li><i class="ti-twitter-alt"></i> <a href="#">Twitter</a></li>
                                <li><i class="ti-google"></i> <a href="#">Google+</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="footer-widget">
                            <h4>Contact Us</h4>
                            <ul class="contact-option">
                                <li><i class="fa fa-map-marker"></i> 16 Creek Ave. Farming, NY</li>
                                <li><i class="fa fa-phone"></i> (+88) 666 121 4321</li>
                                <li><i class="fa fa-envelope"></i> info.colorlib@gmail.com</li>
                                <li><i class="fa fa-clock-o"></i> Mon - Sat, 08 AM - 06 PM</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright-text">
                <p><p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p></p>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Js Plugins -->
    <script src="~/Content/Front/js/jquery-3.3.1.min.js"></script>
    <script src="~/Content/Front/js/bootstrap.min.js"></script>
    <script src="~/Content/Front/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/Front/js/jquery.nice-select.min.js"></script>
    <script src="~/Content/Front/js/jquery.slicknav.js"></script>
    <script src="~/Content/Front/js/jquery-ui.min.js"></script>
    <script src="~/Content/Front/js/owl.carousel.min.js"></script>
    <script src="~/Content/Front/js/main.js"></script>
    @RenderSection("scripts", required: false)
</body>

</html>